### ISSUE TITLE
Kitchen Cabinet quick lighting

### ISSUE THREAD

**Issue by lcalvert7495** [Pixelcontroller/f-prop_issues#1]
I've just started my build for the F-Prop to control 3 pixel pucks that will be at the top and bottom of downstairs kitchen cabinets.

Looks like the board takes about 5 seconds to start up and run the config to output to lights... @keithsw1111 any thoughts on reducing.  No need to run all the time as we do not use this but on weekends.

Also, the board itself has built in "tapping" sensor to change lights - I would like to wire a "puck" under the cabinet to cause the change of lights...either colors or brightness.

Lastly, will start research on internal clock for Date and time so the F-Prop will compute date at start up and display proper simple sequence (July = Red, White, Blue; Christmas = Red/Green; October = Purple/Orange) etc.

It's going to be a big learning curve for me!

Larry Calvert
Greenwood, Indiana
Indiana Christmas Mini

**Comment by dpitts** [comment]
Hi,

We received your request and will respond shortly.
Please use “Reply All” to ensure support team receives all emails.

Thank you,

David Pitts
***@***.***

From: lcalvert7495 ***@***.***>
Sent: Saturday, May 18, 2024 5:23 PM
To: Pixelcontroller/f-prop_issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pixelcontroller/f-prop_issues] Kitchen Cabinet quick lighting (Issue #1)


I've just started my build for the F-Prop to control 3 pixel pucks that will be at the top and bottom of downstairs kitchen cabinets.

Looks like the board takes about 5 seconds to start up and run the config to output to lights... @keithsw1111<https://github.com/keithsw1111> any thoughts on reducing. No need to run all the time as we do not use this but on weekends.

Also, the board itself has built in "tapping" sensor to change lights - I would like to wire a "puck" under the cabinet to cause the change of lights...either colors or brightness.

Lastly, will start research on internal clock for Date and time so the F-Prop will compute date at start up and display proper simple sequence (July = Red, White, Blue; Christmas = Red/Green; October = Purple/Orange) etc.

It's going to be a big learning curve for me!

Larry Calvert
Greenwood, Indiana
Indiana Christmas Mini

**Comment by keithsw1111** [comment]
I will look into it. Having a SD card (with no FL3 and fep.cfg) will help as it is the SD card checking that takes most of that time. I may be able to reduce to about half that time but no less.

I am not sure what you mean by "wire a "puck" under the cabinet to cause the change of lights...either colors or brightness" ... you could wire buttons to do what you describe. Just wire each between ground and 1 of the 6 input pins.

There is no real time clock or current ability to talk to one so a time of year solution is not really there. While i could allow it to talk to a RTC using the input pins you would lose those pins as input pins (it is possible i could get it down to 2 only pins) and there would need to be some substantial changes to add the use of the clock in the configuration.

**Comment by keithsw1111** [comment]
Next version of firmware (build 4) will have some startup improvements. We cant fix them all as this slowness is also in the bootloader and it is not field updateable.

**Comment by lcalvert7495** [comment]
Thank you, Sir!  I will give feedback to assist you and stay out of your way.

Larry Calvert
***@***.***
You Matter to God!
317-919-3402


From: Keith Westley ***@***.***>
Date: Thursday, May 23, 2024 at 6:41 AM
To: Pixelcontroller/f-prop_issues ***@***.***>
Cc: lcalvert7495 ***@***.***>, Author ***@***.***>
Subject: Re: [Pixelcontroller/f-prop_issues] Kitchen Cabinet quick lighting (Issue #1)

Next version of firmware (build 4) will have some startup improvements. We cant fix them all as this slowness is also in the bootloader and it is not field updateable.
