### ISSUE TITLE
What is correct setup for loading several fseq and just play them in order when programming via the webtool

### ISSUE THREAD

**Issue by patdelaney** [Pixelcontroller/f-prop_issues#2]
I am running build 6. The use case is upload 2 files to SD card, and playthem when unit powers on. The first file is a staic all lights on, the second file has flashing pixels. When I boot up F-Prop the 2nd file (flashing pixes) loads and it just loops that one.
There may be a descrpeancy bewteen the examples in the doumentation and whe you can do with the tool.

Here is how I confiured with the tool. (see full image below)
I uplaoded the 2 fseq files
I configured the plater as Play FSEQ Animation from SD card
SD Card: Sequenctial
First File (0 for all files) :0
Last File (0 for all files) :0

Making the assumption that it would start at 001 and finish on 002
It only loops the 2nd file.
![image](https://github.com/user-attachments/assets/88540392-b7e3-4e51-8ca7-342decedfadc)

I'll attach the logs and raw files in case you want to test it out.
[f-prop_Delaney.zip](https://github.com/user-attachments/files/16619521/f-prop_Delaney.zip)

I'm not sure what this means:
[00540839] [0] Attempt to read past end of FSEQ 1200.
[00540860] [0]    Frame MS: 25, Frames: 1200, Frame Size: 2760, Header Length: 68
[00540867] [0]    V2 Format.
[00540874] [0]    Sparse Ranges: 0
[00540880] [0]    Uncompressed.

**Comment by keithsw1111** [comment]
Build 7 should fix this issue.

**Comment by patdelaney** [comment]
This is how I configured it, static image was 001 and flashing as 002. When I booted it up it played flashing first then static
[fep.log](https://github.com/user-attachments/files/16645456/fep.log)

**Comment by keithsw1111** [comment]
Yeah ... it does that ... it plays the second first ... let me see if i can solve it.

**Comment by lcalvert7495** [comment]
Thank you, Keith. I’m still hopeful you can greatly reduce start up time. I’m uncomfortable with the mean well always on above my cabinets. Thank you for your continued support. God blessLarryLarry CalvertYou Matter to God!Cell: 317-919-3402Email: ***@***.*** from my Mobile DeviceOn Aug 17, 2024, at 7:27 PM, Keith Westley ***@***.***> wrote:﻿
Yeah ... it does that ... it plays the second first ... let me see if i can solve it.

**Comment by keithsw1111** [comment]
This will fix the play second issue.

Startup there really is nothing more I can do other than say a SD card in the slot dramatically shortens it. The slowness is all down to the library checking for the SD card and I have optimised that as much as I can without making SD reading unreliable.

Keith
