### ISSUE TITLE
Enhancement: Add remember last Frame check box to hold last frame of data on the prop until the next sequence starts

### ISSUE THREAD

**Issue by patdelaney** [Pixelcontroller/f-prop_issues#3]
Basically when F-Prop switches between sequences the prop goes black for maybe 1/2 second or less. Would it be possible to add a check box to remember the last frame of data and hold it until next sequence starts.

The reason for the checkbox is that not every use case would require that functionality. It should not rember last frame if it's the last sequnce playing. (use case would be to not do that when sequences are started via triggers)

**Comment by keithsw1111** [comment]
I sent you a beta of a change which i think addresses this in a better way.

**Comment by lcalvert7495** [comment]
Thank you Keith. I will try the change.

God bless,

Larry

Larry Calvert
***@***.***
You Matter to God!
317-919-3402


From: Keith Westley ***@***.***>
Date: Tuesday, August 20, 2024 at 7:12 AM
To: Pixelcontroller/f-prop_issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Pixelcontroller/f-prop_issues] Enhancement: Add remember last Frame check box to hold last frame of data on the prop until the next sequence starts (Issue #3)

I sent you a beta of a change which i think addresses this in a better way.
