### ISSUE TITLE
single button step through fseqs in repeat not doable

### ISSUE THREAD

**Issue by piquantsteve** [Pixelcontroller/f-prop_issues#5]
I have a simple playback scenario that I don’t believe is doable with the current setup but believe it could be a very common need..

I have exhibit and want a single button to step through choices of fseq sequences (no audio). Playing each in repeat (looping) until another button event takes place.

I have an fseq for each animated effect.

On power it i can get it to play a chosen fseq in play mode no problem.
My issue is with event mode and stepping through the animations with a single button.

I want to then index through each fseq animation with a pushbutton and then play that fseq animation in repeat until the next button event indexes to the next effect.

I tried all combinations of settings but no luck. I know from the manual that index is not available in play mode but to get it running I need a second switch to just get me into event mode before I can use index.

Is there any way to go directly from play mode to an index operation or a way to trigger a startup event that would get me in event mode on power up?

Am I missing a trick here on how to do this? Or is this ‘single button step through fseqs in repeat’ an operational mode you could support in a future release?. Thanks

**Comment by keithsw1111** [comment]
This option does exist. I will post a sample CFG tonight that does this.

**Comment by keithsw1111** [comment]
Something like this:

# Generated by fep.html
# This version of the tool targets build 10
# Timestamp: 29/10/2024, 21:09:09

# Pixel Output
stringPixels_1=100
stringPixels_2=100

# Audio Output

# Flash Files
File_1=colouredbars.fseq
File_2=pink.fseq
File_3=rainbow.fseq

# Player
playerMode=PlayFSEQ
playerParam_A=0xFF02
playerParam_B=0
playerParam_C=0

# Events

# Event 1
eventMode_1=Index
eventParam_A_1=1
eventTrigger_1=SensorNOPoll_1
sensorSensitivity_1=50
eventAction_1=Immediate
sensorGap_1=100


# Miscelaneous

**Comment by keithsw1111** [comment]
The 0xFF02 says play sequences sequentially but loop the current sequence. The event then moves to the next sequence.
